#ifndef VVCOMMONACTORSHEADER_H_
#define VVCOMMONACTORSHEADER_H_
#include "jp/gecchi/VioletVreath/VioletVreath.h"

#include "jp/gecchi/VioletVreath/actor/common/laserchip/EnemyStraightLaserChip001.h"
#include "jp/gecchi/VioletVreath/actor/common/laserchip/EnemyWateringLaserChip001.h"
#include "jp/gecchi/VioletVreath/actor/common/mesh/GroundMeshActor.h"
#include "jp/gecchi/VioletVreath/actor/common/shot/Shot001.h"
#include "jp/gecchi/VioletVreath/actor/common/shot/Shot002.h"
#include "jp/gecchi/VioletVreath/actor/common/shot/Shot003.h"
#include "jp/gecchi/VioletVreath/actor/common/shot/Shot004.h"
#include "jp/gecchi/VioletVreath/actor/common/shot/Shot004Blue.h"
#include "jp/gecchi/VioletVreath/actor/common/shot/Shot004Yellow.h"
#include "jp/gecchi/VioletVreath/actor/common/TestDepository.h"

#include "jp/gecchi/VioletVreath/actor/effect/Blink/EffectBlink.h"
#include "jp/gecchi/VioletVreath/actor/effect/Blink/EffectBlink001.h"
#include "jp/gecchi/VioletVreath/actor/effect/Blink/EffectBlink002.h"
#include "jp/gecchi/VioletVreath/actor/effect/Blink/EffectBlink003.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectCondensation001.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectExplosion001.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectExplosion002.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectExplosion003.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectExplosion004.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectLaserRefraction001.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectTurbo001.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectTurbo002.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectWormhole.h"
#include "jp/gecchi/VioletVreath/actor/effect/EffectWormhole001.h"

#include "jp/gecchi/VioletVreath/actor/item/Item.h"
#include "jp/gecchi/VioletVreath/actor/item/MagicPointItem.h"
#include "jp/gecchi/VioletVreath/actor/item/MagicPointItem001.h"
#include "jp/gecchi/VioletVreath/actor/item/MagicPointItem002.h"
#include "jp/gecchi/VioletVreath/actor/item/MagicPointItem003.h"
#include "jp/gecchi/VioletVreath/actor/item/ScoreItem.h"
#include "jp/gecchi/VioletVreath/actor/item/ScoreItem001.h"
#include "jp/gecchi/VioletVreath/actor/item/VreathItem.h"
#include "jp/gecchi/VioletVreath/actor/item/VreathItem001.h"

#include "jp/gecchi/VioletVreath/actor/label/LabelBonus001.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelFix16Font01.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelFont16x32.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelFont32x64.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelFont8x16.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelGecchi16Font.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelGecchi32Font.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelGecchi8Font.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelMenuItemFont01.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelMenuTitleFont01.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelRankFont.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelRankingFont.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelSceneSymbol.h"
#include "jp/gecchi/VioletVreath/actor/label/LabelScoreFont.h"
#include "jp/gecchi/VioletVreath/actor/label/SpriteFont32x64.h"
#include "jp/gecchi/VioletVreath/actor/label/SpriteLabelBonus001.h"
#include "jp/gecchi/VioletVreath/actor/label/SpriteLabelGecchi32Font.h"
#include "jp/gecchi/VioletVreath/actor/label/SpriteLabelTest.h"

#include "jp/gecchi/VioletVreath/actor/chikei/wall/Wall01.h"

#endif /*VVCOMMONACTORSHEADER_H_*/
